
from contextlib import suppress
from copy import deepcopy
from cmd_line_interface.auto_close_security_profile_type import auto_close_security_profile_type
from cmd_line_interface.base_defines import AutoCloseFileType, DYNAMIC_HELP_PLURAL, HELP, HELP_GROUP, HELP_HELP, KWARGS_ACTION, KWARGS_APPEND, KWARGS_CHOICES, KWARGS_DEFAULT, KWARGS_HELP, KWARGS_NARGS, KWARGS_READ_BINARY, KWARGS_STORE_TRUE, KWARGS_TYPE, KWARGS_WRITE_BINARY
from cmd_line_interface.basecmdline import CMDLineArgs, update_cmdline_arg
from cmd_line_interface.sectools.cmd_line_common.base_defines import AVAILABLE_SIGNATURE_FORMATS, LOCAL, PLUGIN, PLUGIN_SIGNER, SIGNING_MODE_GROUP, TEST
from cmd_line_interface.sectools.cmd_line_common.defines import AVAILABLE_DEVICE_RESTRICTIONS, AVAILABLE_DEVICE_RESTRICTIONS_COMMON_HELP, AVAILABLE_SEGMENT_HASH_ALGORITHMS, AVAILABLE_VARIANTS, COMMON, COMMON_DEVICE_RESTRICTIONS, COMMON_SIGNING, DEVICE_RESTRICTIONS_GROUP, DUMP, EXTENDED_AVAILABLE_SIGNATURE_FORMATS_HELP, GENERATE, HASH, IMAGE_FORMAT_GROUP, IMAGE_INPUTS_GROUP, IMAGE_OPERATIONS_GROUP, IMAGE_OUTPUTS_GROUP, INDEPENDENT, INFILE, INFILE_HELP, INSPECT, INSPECT_HELP, JTAG_ID, OUTFILE, OUTFILE_HELP, PLATFORM_BINDING, ROOT_CERTIFICATE, SECURITY_PROFILE, SECURITY_PROFILE_GROUP, SECURITY_PROFILE_SINGLE_HELP, SEGMENT_HASH_ALGORITHM, SEGMENT_HASH_ALGORITHMS, SEGMENT_HASH_ALGORITHM_HELP, SERIAL_NUMBER, SERIAL_NUMBER_HELP, SIGN, SIGNING_MODE, SIGNING_MODE_COMMON_HELP_EXTENDED, SOC_HW_VER, VARIANT, VARIANT_HELP, VERBOSE, VERIFY_ROOT, VERIFY_ROOT_HELP, eight_byte_hex
from cmd_line_interface.sectools.metadata import DEPENDS_ON, DEPENDS_ON_ANY_OF, INCOMPATIBLE_WITH, INCOMPATIBLE_WITH_ALL_BUT, VALUE_DEPENDS_ON, VALUE_DEPENDS_ON_ANY_OF
from cmd_line_interface.sectools.secure_image.defines import EXTENDED_AVAILABLE_SEGMENT_HASH_ALGORITHMS_HELP, MANDATE_SECURITY_PROFILE_STRING
NONPUBLIC_FUSE_BLOWER_SIGNING_MODES: list[str] = []
with suppress(ModuleNotFoundError):
    from cmd_line_interface.sectools.nonpublic.nonpublic_defines import NONPUBLIC_COMMON_SIGNING_DEPENDENCIES_VALUE_DEPENDS_ON, NONPUBLIC_COMMON_SIGNING_DEPENDENCIES_VALUE_DEPENDS_ON_ANY_OF, NONPUBLIC_FUSE_BLOWER_SIGNING_MODES
    None(None, None, None)
# WARNING: Decompyle incomplete
