
L3_AD_SIZE = 32
IMAGE_ENCRYPTION_ALGO_AES = 1
IMAGE_ENCRYPTION_ALGO_DESCRIPTION = {
    IMAGE_ENCRYPTION_ALGO_AES: 'AES' }
IMAGE_ENCRYPTION_MODE_CBC_CTS = 1
IMAGE_ENCRYPTION_MODE_DESCRIPTION = {
    IMAGE_ENCRYPTION_MODE_CBC_CTS: 'CBC CTS' }
