
from common.parser.elf.defines import PT_LOAD
P_FLAGS_OS_SEGMENT_L4 = 0
P_FLAGS_OS_SEGMENT_AMSS = 1
P_FLAGS_OS_SEGMENT_HASH = 2
P_FLAGS_OS_SEGMENT_BOOT = 3
P_FLAGS_OS_SEGMENT_L4BSP = 4
P_FLAGS_OS_SEGMENT_SWAPPED = 5
P_FLAGS_OS_SEGMENT_SWAP_POOL = 6
P_FLAGS_OS_SEGMENT_PHDR = 7
UIE_ENCRYPTABLE_SEGMENTS = [
    PT_LOAD]
