
QBEC_MAG = b'CEBQ'
QBEC_VERSION_1 = 1
QBEC_VERSION_2 = 2
QBEC_VERSIONS = [
    QBEC_VERSION_1,
    QBEC_VERSION_2]
XTS_ENCRYPTION_LABEL = b'QTIEncKey'
XTS_BLOCK_SIZE = 16
ENCRYPTING_ENTITY_ID = 0
KEYMANAGEMENT_PARAMETERS_ID = 1
DATA_ENCRYPTION_PARAMETERS_ID = 2
QTI = 0
OEM = 1
ISV = 2
ENCRYPTING_ENTITY_DESCRIPTION = {
    ISV: 'ISV',
    OEM: 'OEM',
    QTI: 'QTI' }
ENCRYPTED_THEN_SIGNED = 0
SIGNED_THEN_ENCRYPTED = 1
ENCRYPTION_ORDER_DESCRIPTION = {
    SIGNED_THEN_ENCRYPTED: 'Signed then Encrypted',
    ENCRYPTED_THEN_SIGNED: 'Encrypted then Signed' }
KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_GCM = 0
KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_XTS = 1
KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_GCM_2 = 2
KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_64_GCM = 3
KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_CMAC_GCM = 4
KEY_MANAGEMENT_SCHEME_ID_GCM_GCM = 5
ECDH_P384_HKDF_SIV_GCM = 'ECDH-P384-HKDF-SIV-GCM'
ECDH_P384_HKDF_SIV_XTS = 'ECDH-P384-HKDF-SIV-XTS'
ECDH_P384_HKDF_SIV_GCM_2 = 'ECDH-P384-HKDF-SIV-GCM-2'
ECDH_P384_HKDF_SIV_64_GCM = 'ECDH-P384-HKDF-SIV-64-GCM'
ECDH_P384_HKDF_SIV_CMAC_GCM = 'ECDH-P384-HKDF-SIV-CMAC-GCM'
GCM_GCM = 'GCM-GCM'
KeyManagementSchemeIDs: list[int] = [
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_GCM,
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_XTS,
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_GCM_2,
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_64_GCM,
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_CMAC_GCM,
    KEY_MANAGEMENT_SCHEME_ID_GCM_GCM]
KEY_MANAGEMENT_SCHEME_DESCRIPTION_TO_ID: dict[(str, int)] = {
    GCM_GCM: KEY_MANAGEMENT_SCHEME_ID_GCM_GCM,
    ECDH_P384_HKDF_SIV_CMAC_GCM: KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_CMAC_GCM,
    ECDH_P384_HKDF_SIV_64_GCM: KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_64_GCM,
    ECDH_P384_HKDF_SIV_GCM_2: KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_GCM_2,
    ECDH_P384_HKDF_SIV_XTS: KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_XTS,
    ECDH_P384_HKDF_SIV_GCM: KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_GCM }
KEY_MANAGEMENT_SCHEME_ID_TO_DESCRIPTION: dict[(int, str)] = (lambda .0: pass# WARNING: Decompyle incomplete
)(KEY_MANAGEMENT_SCHEME_DESCRIPTION_TO_ID.items())
KEY_MANAGEMENT_SCHEME_ID_TO_DIVERSIFIER_LABEL: dict[(int, str)] = {
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_CMAC_GCM: 'QBEC ECDH P384 HKDF AES-SIV CMAC AES-GCM-256',
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_64_GCM: 'QBEC ECDH P384 HKDF AES-SIV-64 AES-GCM-256',
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_GCM_2: 'QBEC ECDH P384 HKDF AES-SIV AES-GCM-256',
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_XTS: 'QBEC ECDH P384 HKDF AES-SIV AES-XTS-256',
    KEY_MANAGEMENT_SCHEME_ID_ECDH_P384_HKDF_SIV_GCM: 'QBEC ECDH P384 HKDF AES-SIV AES-GCM-256' }
KEY_MANAGEMENT_FEATURE_ID_MODEM_IMAGE = 0
KEY_MANAGEMENT_FEATURE_ID_TENX_IMAGE = 1
KEY_MANAGEMENT_FEATURE_ID_FLASH_BINARY = 2
KEY_MANAGEMENT_FEATURE_ID_MODEM_IMAGE_KPV4 = 3
KEY_MANAGEMENT_FEATURE_ID_AUDIO_IMAGE = 4
KEY_MANAGEMENT_FEATURE_ID_GENERIC_TME_CE_IMAGE = 5
KEY_MANAGEMENT_FEATURE_NAME_MODEM_IMAGE = 'MODEM-IMAGE'
KEY_MANAGEMENT_FEATURE_NAME_TENX_IMAGE = 'TENX-IMAGE'
KEY_MANAGEMENT_FEATURE_NAME_FLASH_BINARY = 'FLASH-BINARY'
KEY_MANAGEMENT_FEATURE_NAME_MODEM_IMAGE_KPV4 = 'MODEM-IMAGE-KPV4'
KEY_MANAGEMENT_FEATURE_NAME_AUDIO_IMAGE = 'AUDIO-IMAGE'
KEY_MANAGMENT_FEATURE_NAME_GENERIC_TME_CE_IMAGE = 'GENERIC-TME-CE-IMAGE'
KEY_MANAGEMENT_FEATURE_IDS: list[int] = [
    KEY_MANAGEMENT_FEATURE_ID_MODEM_IMAGE,
    KEY_MANAGEMENT_FEATURE_ID_TENX_IMAGE,
    KEY_MANAGEMENT_FEATURE_ID_FLASH_BINARY,
    KEY_MANAGEMENT_FEATURE_ID_MODEM_IMAGE_KPV4,
    KEY_MANAGEMENT_FEATURE_ID_AUDIO_IMAGE,
    KEY_MANAGEMENT_FEATURE_ID_GENERIC_TME_CE_IMAGE]
KEY_MANAGEMENT_FEATURE_DESCRIPTION_TO_ID: dict[(str, int)] = {
    KEY_MANAGMENT_FEATURE_NAME_GENERIC_TME_CE_IMAGE: KEY_MANAGEMENT_FEATURE_ID_GENERIC_TME_CE_IMAGE,
    KEY_MANAGEMENT_FEATURE_NAME_AUDIO_IMAGE: KEY_MANAGEMENT_FEATURE_ID_AUDIO_IMAGE,
    KEY_MANAGEMENT_FEATURE_NAME_MODEM_IMAGE_KPV4: KEY_MANAGEMENT_FEATURE_ID_MODEM_IMAGE_KPV4,
    KEY_MANAGEMENT_FEATURE_NAME_FLASH_BINARY: KEY_MANAGEMENT_FEATURE_ID_FLASH_BINARY,
    KEY_MANAGEMENT_FEATURE_NAME_TENX_IMAGE: KEY_MANAGEMENT_FEATURE_ID_TENX_IMAGE,
    KEY_MANAGEMENT_FEATURE_NAME_MODEM_IMAGE: KEY_MANAGEMENT_FEATURE_ID_MODEM_IMAGE }
KEY_MANAGEMENT_FEATURE_ID_TO_DESCRIPTION: dict[(int, str)] = (lambda .0: pass# WARNING: Decompyle incomplete
)(KEY_MANAGEMENT_FEATURE_DESCRIPTION_TO_ID.items())
DATA_ENCRYPTION_SCHEME_ID_ELF_SEGMENT_AES_GCM = 0
DATA_ENCRYPTION_SCHEME_ID_AES_128_XTS = 1
ELF_SEGMENT_AES_GCM = 'ELF-SEGMENT-AES-GCM'
AES_128_XTS = 'AES-128-XTS'
DATA_ENCRYPTION_SCHEME_IDS: list[int] = [
    DATA_ENCRYPTION_SCHEME_ID_ELF_SEGMENT_AES_GCM,
    DATA_ENCRYPTION_SCHEME_ID_AES_128_XTS]
DATA_ENCRYPTION_SCHEME_DESCRIPTION_TO_ID: dict[(str, int)] = {
    AES_128_XTS: DATA_ENCRYPTION_SCHEME_ID_AES_128_XTS,
    ELF_SEGMENT_AES_GCM: DATA_ENCRYPTION_SCHEME_ID_ELF_SEGMENT_AES_GCM }
DATA_ENCRYPTION_SCHEME_ID_TO_DESCRIPTION: dict[(int, str)] = (lambda .0: pass# WARNING: Decompyle incomplete
)(DATA_ENCRYPTION_SCHEME_DESCRIPTION_TO_ID.items())
WRAPPED_KEY_POLICY_HEX_LEN = 16
