
from common.crypto.openssl.defines import CURVE_SECP256R1, CURVE_SECP384R1, KEY_SIZE_2048, KEY_SIZE_4096, RSA_PADDING_PKCS, RSA_PADDING_PSS
from common.data.data import tuple_to_version_string
from common.data.defines import SHA256_DESCRIPTION, SHA384_DESCRIPTION, SHA512_DESCRIPTION
from common.parser.elf_with_hash_segment.v6.metadata.defines import METADATA_MAJOR_VERSION_0, METADATA_MAJOR_VERSION_1, METADATA_MINOR_VERSION_0
from common.parser.elf_with_hash_segment.v7.metadata.defines import COMMON_METADATA_MAJOR_VERSION_0, COMMON_METADATA_MINOR_VERSION_0, COMMON_METADATA_MINOR_VERSION_1, METADATA_MAJOR_VERSION_2, METADATA_MAJOR_VERSION_3, METADATA_MINOR_VERSION_1
from common.parser.elf_with_hash_segment.v8.metadata.defines import METADATA_MAJOR_VERSION_4
from common.parser.hash_segment.defines import HASH_SEGMENT_V3, HASH_SEGMENT_V5, HASH_SEGMENT_V6, HASH_SEGMENT_V7, HASH_SEGMENT_V8, MRC_1_0, MRC_2_0, MRC_3_0
from common.parser.sec_dat.defines import SEGMENT_EFUSE_DESCRIPTION, SEGMENT_KEY_PROV_DESCRIPTION
from profile.defines import ANY, END, START
UIE = 'UIE'
QBEC = 'QBEC'
METADATA_VERSION_0_0 = tuple_to_version_string((METADATA_MAJOR_VERSION_0, METADATA_MINOR_VERSION_0))
METADATA_VERSION_1_0 = tuple_to_version_string((METADATA_MAJOR_VERSION_1, METADATA_MINOR_VERSION_0))
METADATA_VERSION_2_0 = tuple_to_version_string((METADATA_MAJOR_VERSION_2, METADATA_MINOR_VERSION_0))
METADATA_VERSION_3_0 = tuple_to_version_string((METADATA_MAJOR_VERSION_3, METADATA_MINOR_VERSION_0))
METADATA_VERSION_3_1 = tuple_to_version_string((METADATA_MAJOR_VERSION_3, METADATA_MINOR_VERSION_1))
METADATA_VERSION_4_0 = tuple_to_version_string((METADATA_MAJOR_VERSION_4, METADATA_MINOR_VERSION_0))
COMMON_METADATA_0_0 = tuple_to_version_string((COMMON_METADATA_MAJOR_VERSION_0, COMMON_METADATA_MINOR_VERSION_0))
COMMON_METADATA_0_1 = tuple_to_version_string((COMMON_METADATA_MAJOR_VERSION_0, COMMON_METADATA_MINOR_VERSION_1))
ENCRYPTED_THEN_SIGNED = 'ENCRYPTED-THEN-SIGNED'
SIGNED_THEN_ENCRYPTED = 'SIGNED-THEN-ENCRYPTED'
ELF_CLASSES = [
    32,
    64]
HASH_ALGORITHMS = [
    SHA256_DESCRIPTION,
    SHA384_DESCRIPTION,
    SHA512_DESCRIPTION]
DEFAULT_SEGMENT_PLACEMENTS = [
    START,
    END]
SUPPORTED_SEGMENT_PLACEMENTS = [
    START,
    END,
    ANY]
HASH_TABLE_SEGMENT_VERSIONS = [
    HASH_SEGMENT_V3,
    HASH_SEGMENT_V5,
    HASH_SEGMENT_V6,
    HASH_SEGMENT_V7,
    HASH_SEGMENT_V8]
V6_METADATA_VERSIONS = [
    METADATA_VERSION_0_0,
    METADATA_VERSION_1_0]
V7_METADATA_VERSIONS = [
    METADATA_VERSION_2_0,
    METADATA_VERSION_3_0,
    METADATA_VERSION_3_1]
V8_METADATA_VERSIONS = [
    METADATA_VERSION_4_0]
COMMON_METADATA_VERSIONS = [
    COMMON_METADATA_0_0,
    COMMON_METADATA_0_1]
VOUCH_SEGMENT_VERSIONS = [
    0]
LICENSE_MANAGER_SEGMENT_VERSIONS = [
    0]
RSA_PADDINGS = [
    RSA_PADDING_PKCS.upper(),
    RSA_PADDING_PSS.upper()]
RSA_KEY_SIZES = [
    KEY_SIZE_2048,
    KEY_SIZE_4096]
RSA_EXPONENTS = [
    3,
    257,
    65537]
ECDSA_CURVES = [
    CURVE_SECP256R1.upper(),
    CURVE_SECP384R1.upper()]
MRC_SPECS = [
    MRC_1_0,
    MRC_2_0,
    MRC_3_0]
ENCRYPTION_SPECS = [
    'UIE-1.0-L2-1.0',
    'UIE-1.0-L2-1.1',
    'UIE-1.0-L2-2.0',
    'UIE-2.0-L2-1.2']
ENCRYPTION_TYPES = [
    UIE,
    QBEC]
ENCRYPTION_ORDERS = [
    ENCRYPTED_THEN_SIGNED,
    SIGNED_THEN_ENCRYPTED]
TME_COMMAND_VERSIONS = [
    '1.0',
    '1.1']
TME_SEQ_TEST_SIGNED_IMAGE_HASH_ALGORITHMS = [
    SHA384_DESCRIPTION,
    SHA512_DESCRIPTION]
FUSE_SEGMENTS_TYPE = [
    SEGMENT_EFUSE_DESCRIPTION,
    SEGMENT_KEY_PROV_DESCRIPTION]
