
from common.data.data import get_lsb
ELFMAG = b'\x7fELF'
E_IDENT_SIZE = 16
ELFCLASSNONE = 0
ELFCLASS32 = 1
ELFCLASS64 = 2
ELFCLASS_DESCRIPTION: dict[(int, str)] = {
    ELFCLASS64: 'ELF64',
    ELFCLASS32: 'ELF32',
    ELFCLASSNONE: str(ELFCLASSNONE) }
ELFCLASS_TO_INT: dict[(int, int)] = {
    ELFCLASS64: 64,
    ELFCLASS32: 32,
    ELFCLASSNONE: ELFCLASSNONE }
INT_TO_ELFCLASS: dict[(int, int)] = (lambda .0: pass# WARNING: Decompyle incomplete
)(ELFCLASS_TO_INT.items())
ELFDATANONE = 0
ELFDATA2LSB = 1
ELFDATA2MSB = 2
ELFDATA_DESCRIPTION: dict[(int, str)] = {
    ELFDATA2MSB: "2's complement, big endian",
    ELFDATA2LSB: "2's complement, little endian",
    ELFDATANONE: str(ELFDATANONE) }
EV_NONE = 0
EV_CURRENT = 1
EV_DESCRIPTION: dict[(int, str)] = {
    EV_CURRENT: '1 (current)',
    EV_NONE: str(EV_NONE) }
ELFOSABI_SYSTEM_V = 0
ELFOSABI_HP_UX = 1
ELFOSABI_NETBSD = 2
ELFOSABI_LINUX = 3
ELFOSABI_GNU_HURD = 4
ELFOSABI_SOLARIS = 6
ELFOSABI_AIX = 7
ELFOSABI_IRIX = 8
ELFOSABI_FREEBSD = 9
ELFOSABI_TRU64 = 10
ELFOSABI_NOVELL_MODESTO = 11
ELFOSABI_OPENBSD = 12
ELFOSABI_OPENVMS = 13
ELFOSABI_NONSTOP_KERNEL = 14
ELFOSABI_AROS = 15
ELFOSABI_FENIX_OS = 16
ELFOSABI_CLOUDABI = 17
# WARNING: Decompyle incomplete
