
from __future__ import annotations
import abc
KeyDerivationFunction = <NODE:27>((lambda : 
def derive(self = None, key_material = None):
'''
        Deterministically generates and returns a new key based on the existing
        key material.
        '''
passderive = None(derive)
def verify(self = None, key_material = None, expected_key = abc.abstractmethod):
'''
        Checks whether the key generated by the key material matches the
        expected derived key. Raises an exception if they do not match.
        '''
passverify = None(verify)), 'KeyDerivationFunction', abc.ABCMeta, **('metaclass',))
