
from cmd_line_interface.base_defines import AutoCloseFileType, COMPATIBLE, HELP, HELP_GROUP, HELP_HELP, KWARGS_ACTION, KWARGS_CHOICES, KWARGS_DEFAULT, KWARGS_HELP, KWARGS_READ_BINARY, KWARGS_STORE_TRUE, KWARGS_TYPE, KWARGS_WRITE_BINARY, OPTIONAL
from cmd_line_interface.basecmdline import CMDLineArgs, CMDLineGroup, update_cmdline_arg
from cmd_line_interface.sectools.cmd_line_common.defines import IMAGE_INPUTS_GROUP, IMAGE_OUTPUTS_GROUP, OUTFILE, eight_byte_hex
from cmd_line_interface.sectools.elf_tool.common.defines import COMMON_HELP, COMMON_SEGMENT_CONFIGURATION, DATA, DATA_HELP, DEFAULTS_TO_0, DEFAULT_0, ELF_CONFIGURATION_GROUP, ELF_ENTRY, ELF_ENTRY_COMMON_HELP, OUTFILE_HELP, SEGMENT_CONFIGURATION_DESCRIPTION, SEGMENT_CONFIGURATION_GROUP
from common.parser.elf.defines import ELFCLASS32, ELFCLASS64, ELFCLASS_TO_INT, EM_ARM, EM_INT_TO_DESCRIPTION, EM_INT_TO_STRING, EM_STRING_TO_INT
GENERATE_DESCRIPTION = 'Generate a new ELF software image containing a segment as specified via Segment Configuration arguments.'
ELF_CLASS = '--elf-class'
ELF_MACHINE_TYPE = '--elf-machine-type'
AVAILABLE_ELF_MACHINE_TYPES = '--available-elf-machine-types'
ELF_CLASS_HELP = 'Defaults to 64.'
ELF_ENTRY_HELP = f'''{ELF_ENTRY_COMMON_HELP} {DEFAULTS_TO_0}'''
AVAILABLE_ELF_MACHINE_TYPES_HELP = f'''Show available {ELF_MACHINE_TYPE} values and exit.'''
DEFAULT_ELF_MACHINE_TYPE = EM_INT_TO_STRING[EM_ARM]
ELF_MACHINE_TYPE_HELP = f'''Architecture of output ELF image. Defaults to {DEFAULT_ELF_MACHINE_TYPE} ({EM_INT_TO_DESCRIPTION[EM_STRING_TO_INT[DEFAULT_ELF_MACHINE_TYPE]]}). Provide {AVAILABLE_ELF_MACHINE_TYPES} for available values.'''
GENERATE_HELP = list(COMMON_HELP)
GENERATE_HELP.append(([
    AVAILABLE_ELF_MACHINE_TYPES], {
    KWARGS_HELP: AVAILABLE_ELF_MACHINE_TYPES_HELP,
    KWARGS_ACTION: KWARGS_STORE_TRUE }))
IMAGE_INPUTS: CMDLineGroup = [
    ([
        DATA], {
        KWARGS_HELP: DATA_HELP,
        KWARGS_TYPE: AutoCloseFileType(KWARGS_READ_BINARY) })]
IMAGE_OUTPUTS: CMDLineGroup = [
    ([
        OUTFILE], {
        KWARGS_HELP: OUTFILE_HELP,
        KWARGS_TYPE: AutoCloseFileType(KWARGS_WRITE_BINARY) })]
ELF_CONFIGURATION: CMDLineGroup = [
    ([
        ELF_CLASS], {
        KWARGS_HELP: ELF_CLASS_HELP,
        KWARGS_DEFAULT: ELFCLASS_TO_INT[ELFCLASS64],
        KWARGS_CHOICES: [
            ELFCLASS_TO_INT[ELFCLASS32],
            ELFCLASS_TO_INT[ELFCLASS64]],
        KWARGS_TYPE: int }),
    ([
        ELF_ENTRY], {
        KWARGS_DEFAULT: DEFAULT_0,
        KWARGS_HELP: ELF_ENTRY_HELP,
        KWARGS_TYPE: eight_byte_hex }),
    ([
        ELF_MACHINE_TYPE], {
        KWARGS_DEFAULT: DEFAULT_ELF_MACHINE_TYPE,
        KWARGS_HELP: ELF_MACHINE_TYPE_HELP,
        KWARGS_TYPE: str })]
ELF_TOOL_GENERATE: CMDLineArgs = {
    (SEGMENT_CONFIGURATION_GROUP, SEGMENT_CONFIGURATION_DESCRIPTION, COMPATIBLE, OPTIONAL): COMMON_SEGMENT_CONFIGURATION,
    ELF_CONFIGURATION_GROUP: ELF_CONFIGURATION,
    IMAGE_OUTPUTS_GROUP: IMAGE_OUTPUTS,
    IMAGE_INPUTS_GROUP: IMAGE_INPUTS,
    HELP_GROUP: GENERATE_HELP }
update_cmdline_arg(ELF_TOOL_GENERATE, HELP, {
    KWARGS_HELP: HELP_HELP,
    KWARGS_ACTION: KWARGS_STORE_TRUE })
