
from common.data.data import get_lsb
FEATURE_TYPE_COMPARISON = 1
FEATURE_TYPE_DESCRIPTION = 'Fuse Validator Comparison'
FEATURE_TYPE_INT_TO_DESCRIPTION = {
    FEATURE_TYPE_COMPARISON: FEATURE_TYPE_DESCRIPTION }
FEATURE_TYPE_MASK = 0xFF000000L
OFF_TARGET_FEATURE_ID = 1
ON_TARGET_FEATURE_ID = 2
OFF_TARGET_DESCRIPTION = 'Off-Target Comparison'
ON_TARGET_DESCRIPTION = 'On-Target Comparison'
FEATURE_ID_INT_TO_DESCRIPTION = {
    ON_TARGET_FEATURE_ID: ON_TARGET_DESCRIPTION,
    OFF_TARGET_FEATURE_ID: OFF_TARGET_DESCRIPTION }
FEATURE_ID_MASK = 16777215
DEFAULT_OPERATION_ID = OFF_TARGET_FEATURE_ID << get_lsb(FEATURE_ID_MASK) | FEATURE_TYPE_COMPARISON << get_lsb(FEATURE_TYPE_MASK)
