
SAIL_HYPERVISOR_DEBUG = 'sail_hypervisor_debug'
SAIL_HYPERVISOR_NON_INVASIVE_DEBUG = 'sail_hypervisor_non_invasive_debug'
SAIL_CORE_0_DEBUG = 'sail_core_0_debug'
SAIL_CORE_0_NON_INVASIVE_DEBUG = 'sail_core_0_non_invasive_debug'
SAIL_CORE_1_DEBUG = 'sail_core_1_debug'
SAIL_CORE_1_NON_INVASIVE_DEBUG = 'sail_core_1_non_invasive_debug'
SAIL_CORE_2_DEBUG = 'sail_core_2_debug'
SAIL_CORE_2_NON_INVASIVE_DEBUG = 'sail_core_2_non_invasive_debug'
SAIL_CORE_3_DEBUG = 'sail_core_3_debug'
SAIL_CORE_3_NON_INVASIVE_DEBUG = 'sail_core_3_non_invasive_debug'
SAIL_CORE_4_DEBUG = 'sail_core_4_debug'
SAIL_CORE_4_NON_INVASIVE_DEBUG = 'sail_core_4_non_invasive_debug'
SAIL_CORE_5_DEBUG = 'sail_core_5_debug'
SAIL_CORE_5_NON_INVASIVE_DEBUG = 'sail_core_5_non_invasive_debug'
