
'''
This file contains the changes and new arguments for the "Image Operations" group as differs from the
cmd_line_interface.sectools.cmd_line_common.defines.
'''
from cmd_line_interface.base_defines import KWARGS_ACTION, KWARGS_DEFAULT, KWARGS_HELP, KWARGS_STORE_TRUE, KWARGS_TYPE, KWARGS_WRITE
from cmd_line_interface.basecmdline import AutoCloseDirType, BaseCMDLine, CMDLineGroup
from cmd_line_interface.sectools.cmd_line_common.defines import DUMP, DUMP_HELP, GENERATE, HASH, INFILE, INSPECT, INSPECT_HELP, OUTFILE, QTI, SECURITY_PROFILE, SIGN, SIGNING_MODE, VERBOSE, VERIFY_ROOT, VERIFY_ROOT_HELP, sha256_sha384_hash
from cmd_line_interface.sectools.metadata import DEPENDS_ON, DEPENDS_ON_ANY_OF, INCOMPATIBLE_WITH, INCOMPATIBLE_WITH_ALL_BUT
from cmd_line_interface.sectools.tme_secure_debug.defines import TME_SECURE_DEBUG_NAME
from cmd_line_interface.sectools.tme_secure_debug.defines.signing import OEM_ELF_USE_CASE_NOTE
NEW_DPR = '--new-dpr'
TME_SECURE_DEBUG_INSPECT_HELP = f'''{INSPECT_HELP} Multiple Security Profiles can be provided via {SECURITY_PROFILE} if inspecting a Debug Policy ELF containing multiple chipset-specific DPRs.'''
TME_SECURE_DEBUG_SIGN_HELP = f'''Add or replace the signature of {INFILE} or newly generated TME Debug Policy image. Also add or replace the certificate chain of {INFILE} or newly generated TME Debug Policy image if signing an OEM Debug Policy ELF.'''
TME_SECURE_DEBUG_HASH_HELP = f'''Add or replace the Hash Table Segment of {INFILE} or newly generated OEM Debug Policy ELF. Cannot be used with {QTI}.'''
TME_SECURE_DEBUG_GENERATE_HELP = f'''Generate a new TME Debug Policy image. A QTI Debug Policy Request (DPR) binary will be generated if operating in QTI mode. When operating in OEM mode, an OEM Debug Policy ELF or OEM DPR will be generated depending on the Security Profile. If generating an OEM Debug Policy ELF, multiple OEM DPRs can be generated at once by clustering the arguments of each desired DPR via {NEW_DPR}. Chipset-specific DPRs can be generated by providing {SECURITY_PROFILE} within each cluster. For example: {BaseCMDLine.TOOL_NAME} {TME_SECURE_DEBUG_NAME} <first OEM DPR args> {NEW_DPR} <second OEM DPR args> ...'''
TME_IMAGE_OPERATIONS_GROUP: CMDLineGroup = [
    ([
        INSPECT], {
        KWARGS_HELP: TME_SECURE_DEBUG_INSPECT_HELP,
        KWARGS_DEFAULT: False,
        KWARGS_ACTION: KWARGS_STORE_TRUE }, {
        DEPENDS_ON: [
            INFILE],
        INCOMPATIBLE_WITH_ALL_BUT: [
            INFILE,
            SECURITY_PROFILE,
            VERBOSE] }),
    ([
        DUMP], {
        KWARGS_HELP: DUMP_HELP,
        KWARGS_TYPE: AutoCloseDirType(KWARGS_WRITE) }, {
        DEPENDS_ON: [
            INFILE],
        INCOMPATIBLE_WITH_ALL_BUT: [
            INFILE,
            VERBOSE] }),
    ([
        SIGN], {
        KWARGS_HELP: TME_SECURE_DEBUG_SIGN_HELP,
        KWARGS_DEFAULT: False,
        KWARGS_ACTION: KWARGS_STORE_TRUE }, {
        DEPENDS_ON_ANY_OF: [
            INFILE,
            GENERATE],
        DEPENDS_ON: [
            SIGNING_MODE,
            OUTFILE] }),
    ([
        HASH], {
        KWARGS_HELP: TME_SECURE_DEBUG_HASH_HELP,
        KWARGS_DEFAULT: False,
        KWARGS_ACTION: KWARGS_STORE_TRUE }, {
        DEPENDS_ON_ANY_OF: [
            INFILE,
            GENERATE],
        INCOMPATIBLE_WITH: [
            QTI] }),
    ([
        GENERATE], {
        KWARGS_HELP: TME_SECURE_DEBUG_GENERATE_HELP,
        KWARGS_DEFAULT: False,
        KWARGS_ACTION: KWARGS_STORE_TRUE }, {
        DEPENDS_ON_ANY_OF: [
            HASH,
            SIGN],
        DEPENDS_ON: [
            OUTFILE] }),
    ([
        VERIFY_ROOT], {
        KWARGS_HELP: VERIFY_ROOT_HELP + OEM_ELF_USE_CASE_NOTE,
        KWARGS_TYPE: sha256_sha384_hash }, {
        DEPENDS_ON: [
            INFILE],
        INCOMPATIBLE_WITH_ALL_BUT: [
            INFILE,
            SECURITY_PROFILE,
            VERBOSE] })]
