"""OpenSSL crypto module for secure image signing.

This module provides cryptographic operations based on decompiled
analysis of sectools.exe OpenSSL integration.
"""

from .openssl import (
    get_signature_information,
    extract_signature_format,
    verify_signature,
    verify_certificate_chain,
    get_text_from_certificate,
    convert_certificate_chain_to_format,
    get_all_r_s_sizes,
    get_unsupported_r_s_sizes_in_signing_assets_text,
    validate_signature_and_certificate_format_supported,
    sanitize_certificate_chain,
    refresh_ou_data,
    validate_certificate_chain_depth,
    validate_number_of_root_certificates,
    validate_root_certificate_count_against_mrc_spec,
    validate_signature_format_supported,
    requires_rs_48_49,
    get_signature_algorithm,
    get_ecdsa_curves,
    get_default_ecdsa_curve,
    get_supported_certificate_chain_depths,
    get_default_certificate_chain_depth,
    get_default_root_certificate_count,
    get_supported_signature_formats,
    get_supported_rs_sizes,
    get_min_rs_size,
    load_private_key,
    load_public_key,
    load_certificate,
    sign_data,
    generate_key_pair,
)

__all__ = [
    'get_signature_information',
    'extract_signature_format',
    'verify_signature',
    'verify_certificate_chain',
    'get_text_from_certificate',
    'convert_certificate_chain_to_format',
    'get_all_r_s_sizes',
    'get_unsupported_r_s_sizes_in_signing_assets_text',
    'validate_signature_and_certificate_format_supported',
    'sanitize_certificate_chain',
    'refresh_ou_data',
    'validate_certificate_chain_depth',
    'validate_number_of_root_certificates',
    'validate_root_certificate_count_against_mrc_spec',
    'validate_signature_format_supported',
    'requires_rs_48_49',
    'get_signature_algorithm',
    'get_ecdsa_curves',
    'get_default_ecdsa_curve',
    'get_supported_certificate_chain_depths',
    'get_default_certificate_chain_depth',
    'get_default_root_certificate_count',
    'get_supported_signature_formats',
    'get_supported_rs_sizes',
    'get_min_rs_size',
    'load_private_key',
    'load_public_key',
    'load_certificate',
    'sign_data',
    'generate_key_pair',
]
