
from dataclasses import dataclass
from typing import List, Tuple
DEBUG_POLICY_V_ABSTRACT = 0
DEBUG_POLICY_V1 = 1
DEBUG_POLICY_V2 = 2
DEBUG_POLICY_V3 = 3
DEBUG_POLICY_V4 = 4
DEBUG_POLICY_V5 = 5
DEBUG_POLICY_V6 = 6
DEBUG_POLICY_V7 = 7
DEBUG_POLICY_V8 = 8
SUPPORTED_DEBUG_POLICY_VERSIONS = [
    DEBUG_POLICY_V1,
    DEBUG_POLICY_V2,
    DEBUG_POLICY_V3,
    DEBUG_POLICY_V4,
    DEBUG_POLICY_V5,
    DEBUG_POLICY_V6,
    DEBUG_POLICY_V7,
    DEBUG_POLICY_V8]
DEBUG_POLICY_MAG = b'DBGP'
OEM_DESIGNATED_LOWEST_BIT = 48
OEM_DESIGNATED_HIGHEST_BIT = 63
OEM_DESIGNATED_FLAG_INDICES = list(range(OEM_DESIGNATED_LOWEST_BIT, OEM_DESIGNATED_HIGHEST_BIT + 1))
DebugOption = dataclass(<NODE:12>)
ONLINE_CRASH_DUMPS = 'ONLINE-CRASH-DUMPS'
OFFLINE_CRASH_DUMPS = 'OFFLINE-CRASH-DUMPS'
LOGS = 'LOGS'
JTAG_DEBUG = 'JTAG-DEBUG'
HLOS_TRACES = 'HLOS-TRACES'
ADSP_HLOS_TRACES = 'ADSP-HLOS-TRACES'
MODEM_TRACES = 'MODEM-TRACES'
ALL_TRACES = 'ALL-TRACES'
JTAG_DEBUG_HLOS_TRACES = 'JTAG-DEBUG-HLOS-TRACES'
JTAG_DEBUG_ADSP_HLOS_TRACES = 'JTAG-DEBUG-ADSP-HLOS-TRACES'
JTAG_DEBUG_MODEM = 'JTAG-DEBUG-MODEM'
NON_SECURE_CRASH_DUMPS = 'NONSECURE-CRASH-DUMPS'
APPS_ENCRYPTED_MINI_DUMPS = 'APPS-ENCRYPTED-MINI-DUMPS'
MPSS_ENCRYPTED_MINI_DUMPS = 'MPSS-ENCRYPTED-MINI-DUMPS'
LPASS_ENCRYPTED_MINI_DUMPS = 'LPASS-ENCRYPTED-MINI-DUMPS'
CSS_ENCRYPTED_MINI_DUMPS = 'CSS-ENCRYPTED-MINI-DUMPS'
ADSP_ENCRYPTED_MINI_DUMPS = 'ADSP-ENCRYPTED-MINI-DUMPS'
CDSP_ENCRYPTED_MINI_DUMPS = 'CDSP-ENCRYPTED-MINI-DUMPS'
WLAN_ENCRYPTED_MINI_DUMPS = 'WLAN-ENCRYPTED-MINI-DUMPS'
EUD_UART = 'EUD-UART'
SILENT_LOGGING = 'SILENT-LOGGING'
MODEM_SSR_DUMP = 'MODEM-SSR-DUMP'
MODEM_RESTART = 'MODEM-RESTART'
WLAN_RESTART_DUMP = 'WLAN-RESTART-DUMP'
WLAN_RESTART = 'WLAN-RESTART'
ATB = 'ATB'
QTI_TEST_ROOT_CERTIFICATE_HASH = 'QTI-TEST-ROOT-CERTIFICATE-HASH'
ONLINE_CRASH_DUMPS_HELP = 'Specific to Windows devices. Enable RAM dumps after device has booted to HLOS. Dumps can be collected regardless of whether device resets.'
OFFLINE_CRASH_DUMPS_HELP = 'Enable RAM dumps. Dumps can only be collected after device resets.'
LOGS_HELP = 'Enable QTEE and Trusted Application logging.'
HLOS_TRACES_HELP = 'Enable traces for HLOS.'
ADSP_HLOS_TRACES_HELP = 'Enable traces for ADSP and HLOS.'
MODEM_TRACES_HELP = 'Enable traces for Modem Subsystem.'
ALL_TRACES_HELP = 'Enable traces for QTEE, ADSP, and HLOS.'
JTAG_DEBUG_HLOS_TRACES_HELP = 'Enable JTAG debugging and traces for HLOS.'
JTAG_DEBUG_ADSP_HLOS_TRACES_HELP = 'Enable JTAG debugging and traces for ADSP and HLOS.'
JTAG_DEBUG_MODEM_HELP = 'Enable JTAG debugging and traces for Modem subsystem.'
DEBUG_FLAG_JTAG_DEBUG_HELP = 'Enable JTAG debugging and traces for all subsystems.'
NON_SECURE_CRASH_DUMPS_HELP = 'Enable crash dumps of memory other than QTEE/QSEE secure regions. QTEE Diag log region is encrypted.'
APPS_ENCRYPTED_MINI_DUMPS_HELP = 'Enable encrypted mini dumps for APPS.'
MPSS_ENCRYPTED_MINI_DUMPS_HELP = 'Enable encrypted mini dumps for MPPS.'
LPASS_ENCRYPTED_MINI_DUMPS_HELP = 'Enable encrypted mini dumps for LPASS.'
CSS_ENCRYPTED_MINI_DUMPS_HELP = 'Enable encrypted mini dumps for CSS.'
ADSP_ENCRYPTED_MINI_DUMPS_HELP = 'Enable encrypted mini dumps for ADSP.'
CDSP_ENCRYPTED_MINI_DUMPS_HELP = 'Enable encrypted mini dumps for CDSP.'
WLAN_ENCRYPTED_MINI_DUMPS_HELP = 'Enable encrypted mini dumps for WLAN.'
CRASH_DUMPS_OPTIONS = [
    DebugOption(ONLINE_CRASH_DUMPS, True, [
        0], ONLINE_CRASH_DUMPS_HELP),
    DebugOption(OFFLINE_CRASH_DUMPS, True, [
        1], OFFLINE_CRASH_DUMPS_HELP)]
V1_DEBUG_OPTIONS = CRASH_DUMPS_OPTIONS + [
    DebugOption(LOGS, True, [
        4], LOGS_HELP)]
V2_DEBUG_OPTIONS = CRASH_DUMPS_OPTIONS + [
    DebugOption(JTAG_DEBUG, True, [
        2], DEBUG_FLAG_JTAG_DEBUG_HELP),
    DebugOption(LOGS, True, [
        3], LOGS_HELP)]
V3_DEBUG_OPTIONS = V2_DEBUG_OPTIONS + [
    DebugOption(NON_SECURE_CRASH_DUMPS, False, [
        24], NON_SECURE_CRASH_DUMPS_HELP),
    DebugOption(APPS_ENCRYPTED_MINI_DUMPS, False, [
        25], APPS_ENCRYPTED_MINI_DUMPS_HELP),
    DebugOption(MPSS_ENCRYPTED_MINI_DUMPS, False, [
        26], MPSS_ENCRYPTED_MINI_DUMPS_HELP),
    DebugOption(LPASS_ENCRYPTED_MINI_DUMPS, False, [
        27], LPASS_ENCRYPTED_MINI_DUMPS_HELP),
    DebugOption(CSS_ENCRYPTED_MINI_DUMPS, False, [
        28], CSS_ENCRYPTED_MINI_DUMPS_HELP),
    DebugOption(ADSP_ENCRYPTED_MINI_DUMPS, False, [
        29], ADSP_ENCRYPTED_MINI_DUMPS_HELP),
    DebugOption(CDSP_ENCRYPTED_MINI_DUMPS, False, [
        30], CDSP_ENCRYPTED_MINI_DUMPS_HELP)]
V4_DEBUG_OPTIONS = V3_DEBUG_OPTIONS
V5_DEBUG_OPTIONS = V4_DEBUG_OPTIONS + [
    DebugOption(JTAG_DEBUG_MODEM, True, [
        4], JTAG_DEBUG_MODEM_HELP),
    DebugOption(MODEM_TRACES, True, [
        5], MODEM_TRACES_HELP),
    DebugOption(JTAG_DEBUG_ADSP_HLOS_TRACES, True, [
        6,
        7], JTAG_DEBUG_ADSP_HLOS_TRACES_HELP),
    DebugOption(JTAG_DEBUG_HLOS_TRACES, True, [
        6,
        8], JTAG_DEBUG_HLOS_TRACES_HELP),
    DebugOption(ADSP_HLOS_TRACES, True, [
        7], ADSP_HLOS_TRACES_HELP),
    DebugOption(HLOS_TRACES, True, [
        8], HLOS_TRACES_HELP),
    DebugOption(ALL_TRACES, True, [
        7,
        8], ALL_TRACES_HELP),
    DebugOption(WLAN_ENCRYPTED_MINI_DUMPS, False, [
        31], WLAN_ENCRYPTED_MINI_DUMPS_HELP)]
DEBUG_POLICY_VERSION_TO_OPTIONS = {
    DEBUG_POLICY_V5: V5_DEBUG_OPTIONS,
    DEBUG_POLICY_V4: V4_DEBUG_OPTIONS,
    DEBUG_POLICY_V3: V3_DEBUG_OPTIONS,
    DEBUG_POLICY_V2: V2_DEBUG_OPTIONS,
    DEBUG_POLICY_V1: V1_DEBUG_OPTIONS }
