
from argparse import ArgumentTypeError, SUPPRESS
from contextlib import suppress
from functools import partial
from operator import mul
from cmd_line_interface.auto_close_security_profile_type import auto_close_security_profile_type
from cmd_line_interface.base_defines import AutoCloseFileType, COMPATIBLE, DYNAMIC_HELP_PLURAL, DYNAMIC_HELP_SINGULAR, HELP, HELP_ABBREV, HELP_GROUP, HELP_HELP, KWARGS_ACTION, KWARGS_CHOICES, KWARGS_COUNT, KWARGS_DEFAULT, KWARGS_HELP, KWARGS_NARGS, KWARGS_READ_BINARY, KWARGS_STORE_TRUE, KWARGS_TYPE, KWARGS_WRITE, KWARGS_WRITE_BINARY, LimitedRangeInt, MUTUALLY_EXCLUSIVE, OPTIONAL, OUTFILE_COMMON_HELP
from cmd_line_interface.basecmdline import AutoCloseDirType, CMDLineArgs, update_cmdline_arg
from cmd_line_interface.sectools.cmd_line_common.base_defines import HYBRID_SIGN, HYBRID_SIGN_GROUP, LOCAL, PAD_FOR_HYBRID_SIGN, PLUGIN, PLUGIN_SIGNER, QTI, ROOT_KEY, SECURITY_PROFILE, SIGN, SIGNATURE_FORMAT, SIGNATURE_FORMAT_GROUP, SIGNATURE_FORMAT_HELP, SIGNING_MODE, SIGNING_MODE_COMMON_HELP, SIGNING_MODE_GROUP, TEST
from cmd_line_interface.sectools.metadata import DEPENDS_ON, DEPENDS_ON_ANY_OF, DEPENDS_ON_VALUE, INCOMPATIBLE_WITH, INCOMPATIBLE_WITH_ALL_BUT, INCOMPATIBLE_WITH_VALUE, VALUE_DEPENDS_ON, VALUE_DEPENDS_ON_ANY_OF
from common.crypto.openssl.defines import CERTIFICATE_CHAIN_DEPTHS
from common.data.data import comma_separated_string, hex_string_pad, hex_string_validate
from common.data.defines import HEX_LENGTH_16, HEX_LENGTH_4, HEX_LENGTH_8, HEX_LENGTH_96, SHA256_DESCRIPTION, SHA256_ONE_SHOT_DESCRIPTION, SHA256_ONE_SHOT_ZI_DESCRIPTION, SHA256_ZI_DESCRIPTION, SHA384_DESCRIPTION, SHA384_ONE_SHOT_DESCRIPTION, SHA384_ONE_SHOT_ZI_DESCRIPTION, SHA384_ZI_DESCRIPTION, SHA512_DESCRIPTION, SHA512_ONE_SHOT_DESCRIPTION, SHA512_ONE_SHOT_ZI_DESCRIPTION, SHA512_ZI_DESCRIPTION, SHA_DESCRIPTION_TO_SIZE
from common.parser.elf_with_hash_segment.v7.metadata.defines import DEVELOPMENT_DESCRIPTION, FMR1_DESCRIPTION, FMR2_DESCRIPTION, FMR3_DESCRIPTION, FMR4_DESCRIPTION, HMR1_DESCRIPTION, HMR2_DESCRIPTION, OPERATIONAL_EXT_DESCRIPTION, OPERATIONAL_INT_DESCRIPTION, PRODUCTION_DESCRIPTION, RMA_DESCRIPTION
NONPUBLIC_COMMON_SIGNING_MODES: list[str] | None = None
NONPUBLIC_SIGNING_MODE_COMMON_HELP: str | None = None
NONPUBLIC_SIGNING_MODE_HELP: str | None = None
NONPUBLIC_COMMON_SIGNING: CMDLineArgs = { }
with suppress(ModuleNotFoundError):
    from cmd_line_interface.nonpublic.nonpublic_defines import NONPUBLIC_SIGNING_MODE_COMMON_HELP, NONPUBLIC_SIGNING_MODE_HELP
    from cmd_line_interface.sectools.nonpublic.nonpublic_defines import NONPUBLIC_COMMON_SIGNING_DEPENDENCIES_VALUE_DEPENDS_ON, NONPUBLIC_COMMON_SIGNING_DEPENDENCIES_VALUE_DEPENDS_ON_ANY_OF, NONPUBLIC_COMMON_SIGNING_MODES, NONPUBLIC_COMMON_SIGNING
    None(None, None, None)
# WARNING: Decompyle incomplete
