
SECTION_SIZE = 192
KEY_PAYLOAD_SIZE = 16
ECIES_KEY_PAYLOAD_SIZE = 64
KEY_LADDER_ALGO_AES = 1
KEY_LADDER_ALGO_DESCRIPTION = {
    KEY_LADDER_ALGO_AES: 'AES' }
KEY_LADDER_MODE_CCM = 1
KEY_LADDER_MODE_DESCRIPTION = {
    KEY_LADDER_MODE_CCM: 'CCM' }
