
from common.data.defines import SHA256_DESCRIPTION, SHA384_DESCRIPTION
MULTI_IMAGE_MAG = b'MULT'
MULTI_IMAGE_HASH_ALGO_SHA256 = 2
MULTI_IMAGE_HASH_ALGO_SHA384 = 3
MULTI_IMAGE_HASH_ALGO_DESCRIPTION = {
    MULTI_IMAGE_HASH_ALGO_SHA384: SHA384_DESCRIPTION,
    MULTI_IMAGE_HASH_ALGO_SHA256: SHA256_DESCRIPTION }
MULTI_IMAGE_DESCRIPTION_ALGO = (lambda .0: pass# WARNING: Decompyle incomplete
)(MULTI_IMAGE_HASH_ALGO_DESCRIPTION.items())
MULTI_IMAGE = 'Multi-Image'
