
EPS_MAJOR_VERSION_1 = 1
EPS_MAJOR_VERSION_2 = 2
EPS_MINOR_VERSION_0 = 0
EPSH_MAG = b'EIUQ'
ROOT_KEY_TYPE_RTL_QTI = 0
ROOT_KEY_TYPE_OTP_OEM = 1
ROOT_KEY_TYPE_OTP_QTI = 2
RTL_QTI = 'RTL-QTI'
OTP_OEM = 'OTP-OEM'
OTP_QTI = 'OTP-QTI'
ROOT_KEY_TYPE_DESCRIPTION = {
    ROOT_KEY_TYPE_OTP_QTI: 'OTP QTI',
    ROOT_KEY_TYPE_OTP_OEM: 'OTP OEM',
    ROOT_KEY_TYPE_RTL_QTI: 'RTL QTI' }
ROOT_KEY_TYPE_INT_TO_DESCRIPTION = {
    ROOT_KEY_TYPE_OTP_QTI: OTP_QTI,
    ROOT_KEY_TYPE_OTP_OEM: OTP_OEM,
    ROOT_KEY_TYPE_RTL_QTI: RTL_QTI }
ROOT_KEY_TYPE_DESCRIPTION_TO_INT = (lambda .0: pass# WARNING: Decompyle incomplete
)(ROOT_KEY_TYPE_INT_TO_DESCRIPTION.items())
