
from common.data.defines import SHA256_DESCRIPTION, SHA256_SIZE, SHA384_DESCRIPTION, SHA384_SIZE, SHA512_DESCRIPTION, SHA512_SIZE
METADATA_MAJOR_VERSION_2 = 2
METADATA_MAJOR_VERSION_3 = 3
METADATA_MINOR_VERSION_0 = 0
METADATA_MINOR_VERSION_1 = 1
COMMON_METADATA_MAJOR_VERSION_0 = 0
COMMON_METADATA_MINOR_VERSION_0 = 0
COMMON_METADATA_MINOR_VERSION_1 = 1
FALSE = 1
TRUE = 2
DEBUG_NOP = FALSE
DEBUG_DISABLE = TRUE
DEBUG_ENABLE = 3
FALSE_TRUE_DESCRIPTION = {
    TRUE: 'True',
    FALSE: 'False' }
DEBUG_DESCRIPTION = {
    DEBUG_DISABLE: 'Disable',
    DEBUG_NOP: 'Nop' }
# WARNING: Decompyle incomplete
