
SEC_DAT_VERSION_1 = 1
SEC_DAT_VERSION_2 = 2
SEC_DAT_VERSION_3 = 3
SEC_DAT_SUPPORTED_VERSIONS = [
    SEC_DAT_VERSION_1,
    SEC_DAT_VERSION_2,
    SEC_DAT_VERSION_3]
SEC_DAT_DEFAULT_INFO = b'default dat file'
SEC_DAT_FUSE_VERSION_1 = 1
SEC_DAT_FUSE_VERSION_2 = 2
SEC_DAT_MAGIC1 = 997347786
SEC_DAT_MAGIC2 = 705851177
SEGMENT_EFUSE = 0
SEGMENT_KEY_PROV = 1
SEGMENT_EFUSE_DESCRIPTION = 'efuse'
SEGMENT_KEY_PROV_DESCRIPTION = 'keyprov'
SEGMENT_TYPE_DESCRIPTION = {
    SEGMENT_KEY_PROV: 'Key Provision',
    SEGMENT_EFUSE: 'Efuse' }
SEGMENT_TYPE_DESCRIPTION_TO_INT = {
    SEGMENT_KEY_PROV_DESCRIPTION: SEGMENT_KEY_PROV,
    SEGMENT_EFUSE_DESCRIPTION: SEGMENT_EFUSE }
OEM_SEC_BOOT = 'OEM_SEC_BOOT'
OEM_PK_HASH = 'OEM_PK_HASH'
SEC_HW_KEY = 'SEC_HW_KEY'
OEM_CONFIG = 'OEM_CONFIG'
READ_WRITE_PERM = 'READ_WRITE_PERM'
SPARE_REG19 = 'SPARE_REG19'
GENERAL = 'GENERAL'
FEC_EN = 'FEC_EN'
ANTI_ROLLBACK_1 = 'ANTI_ROLLBACK_1'
ANTI_ROLLBACK_2 = 'ANTI_ROLLBACK_2'
ANTI_ROLLBACK_3 = 'ANTI_ROLLBACK_3'
PK_HASH1 = 'PK_HASH1'
IMAGE_ENCR_KEY1 = 'IMAGE_ENCR_KEY1'
OEM_SECURE = 'OEM_SECURE'
MRC_2_0 = 'MRC_2_0'
OEM_SPARE = 'OEM_SPARE'
READ_PERM = 'READ_PERM'
WRITE_PERM = 'WRITE_PERM'
ANTI_ROLLBACK = 'ANTI_ROLLBACK'
IMAGE_ENCR_KEY = 'IMAGE_ENCR_KEY'
OEM_PRODUCT_SEED = 'OEM_PRODUCT_SEED'
TME_RW_PERM = 'TME_RW_PERM'
TME_FEC_EN = 'TME_FEC_EN'
TME_OEM = 'TME_OEM'
TME_SPARE = 'TME_SPARE'
RFA_CALIBRATION_OEM = 'RFA_CALIBRATION_OEM'
RFA_SW_OEM = 'RFA_SW_OEM'
QC_SPARE = 'QC_SPARE'
# WARNING: Decompyle incomplete
