
from typing import NamedTuple
from common.data.defines import SHA256_DESCRIPTION, SHA384_DESCRIPTION, SHA512_DESCRIPTION
OPENSSL_CERTIFICATE_MODE = 'x509'
FORMAT_PEM = 'PEM'
FORMAT_DER = 'DER'
ALGORITHM_RSA = 'rsa'
ALGORITHM_ECDSA = 'ecdsa'
ALGORITHM_DILITHIUM3 = 'dilithium3'
ALGORITHM_MLDSA65 = 'mldsa65'
ALGORITHM_MLDSA87 = 'mldsa87'
RSA_PADDING_PKCS = 'pkcs'
RSA_PADDING_PSS = 'pss'
RSA_PSS_STR = 'rsassaPss'
RSA_PCKS_STR = 'WithRSAEncryption'
ALGORITHM_RSA_USER_FACING = 'RSA'
ALGORITHM_ECDSA_USER_FACING = 'ECDSA'
ALGORITHM_DILITHIUM3_USER_FACING = 'DILITHIUM3'
ALGORITHM_MLDSA65_USER_FACING = 'ML-DSA-65'
ALGORITHM_MLDSA87_USER_FACING = 'ML-DSA-87'
KEY_SIZE_2048 = 2048
KEY_SIZE_4096 = 4096
CURVE_SECP256R1 = 'secp256r1'
CURVE_SECP384R1 = 'secp384r1'
CURVE_SECP521R1 = 'secp521r1'
RS_48_49 = 'RS-48-49'
CURVE_SECP384R1_RS_48_49 = f'''{CURVE_SECP384R1}-{RS_48_49}'''.upper()
OPENSSL_TO_USER_ALGORITHM_NAMES: dict[(str, str)] = {
    ALGORITHM_MLDSA87: ALGORITHM_MLDSA87_USER_FACING,
    ALGORITHM_MLDSA65: ALGORITHM_MLDSA65_USER_FACING,
    ALGORITHM_DILITHIUM3: ALGORITHM_DILITHIUM3_USER_FACING,
    ALGORITHM_ECDSA: ALGORITHM_ECDSA_USER_FACING,
    ALGORITHM_RSA: ALGORITHM_RSA_USER_FACING }
USER_TO_OPENSSL_ALGORITHM_NAMES = (lambda .0: pass# WARNING: Decompyle incomplete
)(OPENSSL_TO_USER_ALGORITHM_NAMES.items())
PQC_SIGNATURE_ALGORITHMS = [
    ALGORITHM_DILITHIUM3_USER_FACING,
    ALGORITHM_MLDSA65_USER_FACING,
    ALGORITHM_MLDSA87_USER_FACING]
NON_PQC_SIGNATURE_ALGORITHMS = [
    ALGORITHM_RSA_USER_FACING,
    ALGORITHM_ECDSA_USER_FACING]
SUPPORTED_SIGNATURE_ALGORITHMS = NON_PQC_SIGNATURE_ALGORITHMS + PQC_SIGNATURE_ALGORITHMS
X509_V_OK = 0
X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT = 2

class SignatureDescription(NamedTuple):
    key_size_or_curve: int | str | None = 'SignatureDescription'


class SigningAssetsSizes(NamedTuple):
    min_signature_size: int | None = 'SigningAssetsSizes'

(RSA_2K_SIGNATURE_SIZE, RSA_2K_CERTIFICATE_SIZE) = (256, 1440)
(RSA_4K_SIGNATURE_SIZE, RSA_4K_CERTIFICATE_SIZE) = (512, 1940)
(ECDSA_256_SIGNATURE_SIZE, ECDSA_256_CERTIFICATE_SIZE, ECDSA_256_MIN_SIGNATURE_SIZE) = (72, 1060, 66)
(ECDSA_384_SIGNATURE_SIZE, ECDSA_384_CERTIFICATE_SIZE, ECDSA_384_MIN_SIGNATURE_SIZE) = (104, 1120, 73)
(ECDSA_521_SIGNATURE_SIZE, ECDSA_521_CERTIFICATE_SIZE, ECDSA_521_MIN_SIGNATURE_SIZE) = (136, 1200, 105)
(DILITHIUM3_SIGNATURE_SIZE, DILITHIUM3_CERTIFICATE_SIZE) = (3293, 6160)
(MLDSA65_SIGNATURE_SIZE, MLDSA65_CERTIFICATE_SIZE) = (3309, 6180)
(MLDSA87_SIGNATURE_SIZE, MLDSA87_CERTIFICATE_SIZE) = (4627, 8120)
SIGNATURE_DESCRIPTION_TO_SIZE = {
    SignatureDescription(ALGORITHM_MLDSA87_USER_FACING, None): SigningAssetsSizes(MLDSA87_SIGNATURE_SIZE, MLDSA87_CERTIFICATE_SIZE, None),
    SignatureDescription(ALGORITHM_MLDSA65_USER_FACING, None): SigningAssetsSizes(MLDSA65_SIGNATURE_SIZE, MLDSA65_CERTIFICATE_SIZE, None),
    SignatureDescription(ALGORITHM_DILITHIUM3_USER_FACING, None): SigningAssetsSizes(DILITHIUM3_SIGNATURE_SIZE, DILITHIUM3_CERTIFICATE_SIZE, None),
    SignatureDescription(ALGORITHM_ECDSA_USER_FACING, CURVE_SECP521R1.upper()): SigningAssetsSizes(ECDSA_521_SIGNATURE_SIZE, ECDSA_521_CERTIFICATE_SIZE, ECDSA_521_MIN_SIGNATURE_SIZE),
    SignatureDescription(ALGORITHM_ECDSA_USER_FACING, CURVE_SECP384R1.upper()): SigningAssetsSizes(ECDSA_384_SIGNATURE_SIZE, ECDSA_384_CERTIFICATE_SIZE, ECDSA_384_MIN_SIGNATURE_SIZE),
    SignatureDescription(ALGORITHM_ECDSA_USER_FACING, CURVE_SECP256R1.upper()): SigningAssetsSizes(ECDSA_256_SIGNATURE_SIZE, ECDSA_256_CERTIFICATE_SIZE, ECDSA_256_MIN_SIGNATURE_SIZE),
    SignatureDescription(ALGORITHM_RSA_USER_FACING, KEY_SIZE_4096): SigningAssetsSizes(RSA_4K_SIGNATURE_SIZE, RSA_4K_CERTIFICATE_SIZE, None),
    SignatureDescription(ALGORITHM_RSA_USER_FACING, KEY_SIZE_2048): SigningAssetsSizes(RSA_2K_SIGNATURE_SIZE, RSA_2K_CERTIFICATE_SIZE, None) }
SHA_DESCRIPTION_TO_CERTIFICATE_HASH_SIZE: dict[(str, int)] = {
    SHA512_DESCRIPTION: 80,
    SHA384_DESCRIPTION: 60,
    SHA256_DESCRIPTION: 40 }
CERTIFICATE_CHAIN_DEPTHS = [
    2,
    3]
CIPHERNAME_128 = '-aes-128-cbc'
CurveFormats = NamedTuple('CurveFormats', [
    ('normalized_asn1', str),
    ('nist', str)])
CURVE_ASN1_TO_NORMALIZED_ASN1_NIST: dict[(str, CurveFormats)] = {
    'prime256v1': CurveFormats(CURVE_SECP256R1, 'P-256'),
    'secp384r1': CurveFormats(CURVE_SECP384R1, 'P-384'),
    'secp521r1': CurveFormats(CURVE_SECP521R1, 'P-521') }
CURVE_NIST_TO_ASN1 = (lambda .0: pass# WARNING: Decompyle incomplete
)(CURVE_ASN1_TO_NORMALIZED_ASN1_NIST.items())
CURVE_NORMALIZED_ASN1_TO_ASN1 = (lambda .0: pass# WARNING: Decompyle incomplete
)(CURVE_ASN1_TO_NORMALIZED_ASN1_NIST.items())
