
NO_RESPONSE_PAYLOAD_SIZE = 1
VALID_RESPONSE_ACTUAL_PAYLOAD_SIZE = 2
QUERY_TZ_FOR_PAYLOAD_SIZE = 3
NO_RESPONSE_PAYLOAD_SIZE_DESCRIPTION = 'No Response Payload Size'
VALID_RESPONSE_ACTUAL_PAYLOAD_SIZE_DESCRIPTION = 'Valid Response Packet, Actual Payload Size'
QUERY_TZ_FOR_PAYLOAD_SIZE_DESCRIPTION = 'Query TZ For The Size'
RESPONSE_PAYLOAD_SIZE_INT_TO_DESCRIPTION = {
    QUERY_TZ_FOR_PAYLOAD_SIZE: QUERY_TZ_FOR_PAYLOAD_SIZE_DESCRIPTION,
    VALID_RESPONSE_ACTUAL_PAYLOAD_SIZE: VALID_RESPONSE_ACTUAL_PAYLOAD_SIZE_DESCRIPTION,
    NO_RESPONSE_PAYLOAD_SIZE: NO_RESPONSE_PAYLOAD_SIZE_DESCRIPTION }
