
from lzma import FORMAT_ALONE, FORMAT_XZ
XZ = 'XZ'
LZMA = 'LZMA'
COMPRESSION_FORMATS = [
    XZ,
    LZMA]
COMPRESSION_FORMAT_DESCRIPTION_TO_INT: dict[(str, int)] = {
    LZMA: FORMAT_ALONE,
    XZ: FORMAT_XZ }
LZMA_UNCOMPRESSED_DATA_SIZE_OFFSET = 5
LZMA_UNCOMPRESSED_DATA_SIZE_SIZE = 8
LZMA_HEADER_SIZE = LZMA_UNCOMPRESSED_DATA_SIZE_OFFSET + LZMA_UNCOMPRESSED_DATA_SIZE_SIZE
