
from contextlib import suppress
from copy import deepcopy
from cmd_line_interface.auto_close_security_profile_type import auto_close_security_profile_type
from cmd_line_interface.base_defines import AutoCloseFileType, COMPATIBLE, DYNAMIC_HELP_PLURAL, HELP, HELP_GROUP, HELP_HELP, KWARGS_ACTION, KWARGS_APPEND, KWARGS_CHOICES, KWARGS_DEFAULT, KWARGS_HELP, KWARGS_NARGS, KWARGS_READ_BINARY, KWARGS_STORE_TRUE, KWARGS_TYPE, KWARGS_WRITE_BINARY, OPTIONAL
from cmd_line_interface.basecmdline import CMDLineArgs, update_cmdline_arg
from cmd_line_interface.sectools.cmd_line_common.base_defines import AVAILABLE_SIGNATURE_FORMATS, LOCAL, PLUGIN, PLUGIN_SIGNER, SIGNING_MODE
from cmd_line_interface.sectools.cmd_line_common.defines import AUTHORITY, AUTHORITY_GROUP_DESCRIPTION, AVAILABLE_DEVICE_RESTRICTIONS, AVAILABLE_DEVICE_RESTRICTIONS_COMMON_HELP, AVAILABLE_SEGMENT_HASH_ALGORITHMS, AVAILABLE_VARIANTS, COMMON, COMMON_DEVICE_RESTRICTIONS, COMMON_SIGNING, DEVICE_RESTRICTIONS_GROUP, DUMP, EXTENDED_AVAILABLE_SIGNATURE_FORMATS_HELP, GENERATE, HASH, IMAGE_FORMAT_GROUP, IMAGE_INPUTS_GROUP, IMAGE_OPERATIONS_GROUP, IMAGE_OUTPUTS_GROUP, INFILE, INFILE_HELP, INSPECT, OEM_TEST_ROOT_CERTIFICATE_HASH, OEM_TEST_ROOT_CERTIFICATE_HASH_HELP, OUTFILE, OUTFILE_HELP, PLATFORM_BINDING, PLATFORM_BINDINGS, PLATFORM_BINDING_HELP, PRODUCT_SEGMENT_ID, QTI, QTI_TEST_ROOT_CERTIFICATE_HASH_HELP, ROOT_CERTIFICATE, ROOT_CERTIFICATE_HASH_EXTENDED_HELP, ROOT_CERTIFICATE_HASH_GROUP, SECURITY_PROFILE, SECURITY_PROFILE_GROUP, SECURITY_PROFILE_SINGLE_HELP, SEGMENT_HASH_ALGORITHM, SEGMENT_HASH_ALGORITHMS, SEGMENT_HASH_ALGORITHM_HELP, SERIAL_NUMBER, SIGN, SOC_FEATURE_ID, SOC_LIFECYCLE_STATE, SOC_LIFECYCLE_STATES, SOC_LIFECYCLE_STATE_HELP_QTI, VARIANT, VARIANT_HELP, VERBOSE, VERIFY_ROOT, four_byte_hex, sha256_sha384_hash
from cmd_line_interface.sectools.metadata import DEPENDS_ON, DEPENDS_ON_ANY_OF, INCOMPATIBLE_WITH, VALUE_DEPENDS_ON, VALUE_DEPENDS_ON_ANY_OF
from cmd_line_interface.sectools.secure_image.defines import EXTENDED_AVAILABLE_SEGMENT_HASH_ALGORITHMS_HELP, JTAG_DEBUG
from common.parser.debug_policy_elf.defines import DebugOption, OEM_DESIGNATED_FLAG_INDICES
NONPUBLIC_SECURE_DEBUG_SIGNING: CMDLineArgs = { }
with suppress(ModuleNotFoundError):
    from cmd_line_interface.sectools.nonpublic.nonpublic_defines import NONPUBLIC_COMMON_SIGNING_DEPENDENCIES_VALUE_DEPENDS_ON_ANY_OF, NONPUBLIC_SECURE_DEBUG_SIGNING, NONPUBLIC_SIGNING_MODE_VALUE_DEPENDS_ON
    None(None, None, None)
# WARNING: Decompyle incomplete
